import {
  KnowledgeChunk,
  KnowledgeClaim,
  KnowledgeDocument,
  KnowledgeEntity,
  KnowledgeEvidence,
  KnowledgeRelation,
  KnowledgeSource,
} from "@/domain/knowledge/types";

import {
  createKnowledgeSource,
} from "@/domain/knowledge/source-registry";

export const BRAIN_DEMO_NOW =
  "2026-09-23T12:00:00.000Z";

export const demoKnowledgeSources:
  KnowledgeSource[] = [
    createKnowledgeSource({
      id: "source-warpbuild-public",
      name: "WarpBuild public product information",
      type: "PUBLIC_WEB",
      provenance: "PUBLIC",
      description:
        "Public product-level information used by the deterministic Company Brain demonstration.",
      trustScore: 0.85,
      connected: false,
      readOnly: true,
      lastSyncedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        scope:
          "Product positioning only",
      },
    }),

    createKnowledgeSource({
      id: "source-control-plane",
      name: "WARP / CONTROL event and decision plane",
      type: "CONTROL_PLANE",
      provenance: "INTERNAL",
      description:
        "Deterministic control-plane state generated inside the WARP / CONTROL demonstration.",
      trustScore: 1,
      connected: true,
      readOnly: true,
      lastSyncedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        environment:
          "DETERMINISTIC_DEMO",
      },
    }),

    createKnowledgeSource({
      id: "source-demo-account",
      name: "Synthetic Northstar Labs account model",
      type: "MODELED_ANALYSIS",
      provenance: "MODELED",
      description:
        "Synthetic account model used to demonstrate revenue intelligence. It does not represent a real WarpBuild customer.",
      trustScore: 0.6,
      connected: false,
      readOnly: true,
      lastSyncedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        synthetic: true,
      },
    }),

    createKnowledgeSource({
      id: "source-demo-economics",
      name: "CI Economics Model V1.1.0",
      type: "MODELED_ANALYSIS",
      provenance: "MODELED",
      description:
        "Deterministic modeled CI economics used for demonstration and scenario analysis.",
      trustScore: 0.6,
      connected: true,
      readOnly: true,
      lastSyncedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        modelVersion:
          "1.1.0",
      },
    }),

    createKnowledgeSource({
      id: "source-demo-experiments",
      name: "Experiment Intelligence portfolio",
      type: "CONTROL_PLANE",
      provenance: "MODELED",
      description:
        "Deterministic experiment portfolio generated by the experiment intelligence control plane.",
      trustScore: 0.6,
      connected: true,
      readOnly: true,
      lastSyncedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        synthetic: true,
      },
    }),
  ];

export const demoKnowledgeEntities:
  KnowledgeEntity[] = [
    {
      id: "entity-warpbuild",
      type: "COMPANY",
      name: "WarpBuild",
      aliases: [
        "WarpBuild",
      ],
      description:
        "Developer infrastructure company represented in the WARP / CONTROL demonstration.",
      attributes: {},
    },

    {
      id: "entity-warpbuild-ci",
      type: "PRODUCT",
      name: "WarpBuild CI",
      aliases: [
        "WarpBuild CI",
        "CI",
      ],
      description:
        "WarpBuild product focused on faster CI infrastructure.",
      attributes: {},
    },

    {
      id: "entity-helios",
      type: "PRODUCT",
      name: "Helios",
      aliases: [
        "Helios",
      ],
      description:
        "WarpBuild agentic company-knowledge product.",
      attributes: {},
    },

    {
      id: "entity-northstar",
      type: "ACCOUNT",
      name: "Northstar Labs",
      aliases: [
        "Northstar",
        "Northstar Labs",
      ],
      description:
        "Synthetic account used by the revenue intelligence demonstration.",
      attributes: {
        synthetic: true,
        modeledDevelopers: 180,
        modeledRepositories: 74,
      },
    },

    {
      id: "entity-revenue-agent",
      type: "AGENT",
      name: "Revenue Intelligence",
      aliases: [
        "Revenue Agent",
        "Revenue Intelligence",
      ],
      attributes: {},
    },

    {
      id: "entity-experiment-agent",
      type: "AGENT",
      name: "Experiment Analyst",
      aliases: [
        "Experiment Analyst",
      ],
      attributes: {},
    },

    {
      id: "entity-ci-economics",
      type: "METRIC",
      name: "CI Economics",
      aliases: [
        "CI Economics",
        "ROI",
        "CI ROI",
      ],
      attributes: {
        modelVersion:
          "1.1.0",
      },
    },

    {
      id: "entity-experiment-portfolio",
      type: "EXPERIMENT",
      name: "Growth Experiment Portfolio",
      aliases: [
        "Experiment Portfolio",
        "Growth Experiments",
      ],
      attributes: {},
    },

    {
      id: "entity-enterprise-motion",
      type: "CONCEPT",
      name: "Enterprise Sales Motion",
      aliases: [
        "Enterprise Sales",
        "Enterprise Motion",
      ],
      attributes: {},
    },
  ];

export const demoKnowledgeDocuments:
  KnowledgeDocument[] = [
    {
      id: "doc-warpbuild-products",
      sourceId:
        "source-warpbuild-public",
      title:
        "WarpBuild product context",
      content:
        "WarpBuild CI is positioned around faster GitHub Actions CI infrastructure. Helios is an agentic harness for company knowledge. Faster CI can reduce developer feedback-loop waiting when build and test execution is a bottleneck.",
      createdAt:
        BRAIN_DEMO_NOW,
      updatedAt:
        BRAIN_DEMO_NOW,
      effectiveAt:
        BRAIN_DEMO_NOW,
      tags: [
        "warpbuild",
        "product",
        "ci",
        "helios",
      ],
      entityIds: [
        "entity-warpbuild",
        "entity-warpbuild-ci",
        "entity-helios",
      ],
      metadata: {
        provenance:
          "PUBLIC",
      },
    },

    {
      id: "doc-northstar-account",
      sourceId:
        "source-demo-account",
      title:
        "Northstar Labs synthetic account brief",
      content:
        "Northstar Labs is a synthetic demonstration account modeled with 180 developers, 74 repositories and GitHub Actions usage. The account has a WarpScore of 90.8 and is classified STRATEGIC. The modeled annual contract value is $120,000. These values demonstrate account prioritization and do not represent a real WarpBuild customer.",
      createdAt:
        BRAIN_DEMO_NOW,
      updatedAt:
        BRAIN_DEMO_NOW,
      effectiveAt:
        BRAIN_DEMO_NOW,
      tags: [
        "account",
        "revenue",
        "synthetic",
        "warpscore",
      ],
      entityIds: [
        "entity-northstar",
        "entity-revenue-agent",
        "entity-enterprise-motion",
      ],
      metadata: {
        synthetic: true,
        warpScore: 90.8,
      },
    },

    {
      id: "doc-northstar-motion",
      sourceId:
        "source-control-plane",
      title:
        "Northstar revenue decision",
      content:
        "Revenue Intelligence recommends an enterprise discovery motion for the synthetic Northstar Labs account. Human review is required before execution. The next action is to prepare an enterprise discovery brief and identify the buying committee. Procurement ownership is not currently known.",
      createdAt:
        BRAIN_DEMO_NOW,
      updatedAt:
        BRAIN_DEMO_NOW,
      effectiveAt:
        BRAIN_DEMO_NOW,
      tags: [
        "decision",
        "revenue",
        "human-review",
      ],
      entityIds: [
        "entity-northstar",
        "entity-revenue-agent",
        "entity-enterprise-motion",
      ],
      metadata: {
        requiresHumanReview:
          true,
      },
    },

    {
      id: "doc-ci-economics",
      sourceId:
        "source-demo-economics",
      title:
        "CI Economics Model V1.1.0 base scenario",
      content:
        "The deterministic base scenario models 180 developers, four builds per developer per day, twelve baseline minutes per build, 230 engineering days per year, 80 percent adoption and a five-times CI speedup. It produces approximately $391,910 of modeled annual customer value against a $120,000 annual WarpBuild price, or 3.27 times modeled value-to-price. The model is scenario analysis, not observed customer ROI.",
      createdAt:
        BRAIN_DEMO_NOW,
      updatedAt:
        BRAIN_DEMO_NOW,
      effectiveAt:
        BRAIN_DEMO_NOW,
      tags: [
        "economics",
        "roi",
        "modeled",
        "ci",
      ],
      entityIds: [
        "entity-ci-economics",
        "entity-northstar",
        "entity-warpbuild-ci",
      ],
      metadata: {
        modelVersion:
          "1.1.0",
        annualCustomerValue:
          391910,
        annualPrice:
          120000,
        valueToPrice: 3.27,
      },
    },

    {
      id: "doc-experiment-portfolio",
      sourceId:
        "source-demo-experiments",
      title:
        "Experiment Intelligence portfolio decision",
      content:
        "The Experiment Analyst selected three experiments under the current portfolio constraints with $48,000 of modeled allocated budget, $686,200 of modeled expected value and a 14.3 times expected-value-to-cost ratio. Human approval is required before execution. Enterprise security acceleration requires stronger evidence before allocation.",
      createdAt:
        BRAIN_DEMO_NOW,
      updatedAt:
        BRAIN_DEMO_NOW,
      effectiveAt:
        BRAIN_DEMO_NOW,
      tags: [
        "experiments",
        "portfolio",
        "decision",
        "modeled",
      ],
      entityIds: [
        "entity-experiment-agent",
        "entity-experiment-portfolio",
      ],
      metadata: {
        allocatedBudget: 48000,
        modeledExpectedValue:
          686200,
        expectedValueToCost:
          14.3,
      },
    },
  ];

export const demoKnowledgeChunks:
  KnowledgeChunk[] =
    demoKnowledgeDocuments.map(
      (document, index) => ({
        id:
          `chunk-${document.id}-001`,
        documentId:
          document.id,
        sourceId:
          document.sourceId,
        ordinal: 0,
        content:
          document.content,
        tokenEstimate:
          Math.ceil(
            document.content.length /
              4,
          ),
        entityIds:
          document.entityIds,
        tags:
          document.tags,
        createdAt:
          document.createdAt,
      }),
    );

export const demoKnowledgeClaims:
  KnowledgeClaim[] = [
    {
      id: "claim-warpbuild-ci",
      statement:
        "WarpBuild CI is positioned around faster GitHub Actions CI infrastructure.",
      state: "KNOWN",
      provenance: "PUBLIC",
      confidence: 0.85,
      sourceId:
        "source-warpbuild-public",
      documentId:
        "doc-warpbuild-products",
      chunkId:
        "chunk-doc-warpbuild-products-001",
      entityIds: [
        "entity-warpbuild",
        "entity-warpbuild-ci",
      ],
      observedAt:
        BRAIN_DEMO_NOW,
      metadata: {},
    },

    {
      id: "claim-northstar-score",
      statement:
        "Northstar Labs has a modeled WarpScore of 90.8 and is classified STRATEGIC in the deterministic demonstration.",
      state: "MODELED",
      provenance: "MODELED",
      confidence: 0.7616,
      sourceId:
        "source-demo-account",
      documentId:
        "doc-northstar-account",
      chunkId:
        "chunk-doc-northstar-account-001",
      entityIds: [
        "entity-northstar",
      ],
      observedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        warpScore: 90.8,
      },
    },

    {
      id: "claim-northstar-motion",
      statement:
        "Revenue Intelligence recommends enterprise discovery for Northstar Labs and requires human review before execution.",
      state: "KNOWN",
      provenance: "INTERNAL",
      confidence: 0.7658,
      sourceId:
        "source-control-plane",
      documentId:
        "doc-northstar-motion",
      chunkId:
        "chunk-doc-northstar-motion-001",
      entityIds: [
        "entity-northstar",
        "entity-revenue-agent",
        "entity-enterprise-motion",
      ],
      observedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        requiresHumanReview:
          true,
      },
    },

    {
      id: "claim-procurement-owner",
      statement:
        "The procurement owner for Northstar Labs is unknown.",
      state: "UNKNOWN",
      provenance: "INTERNAL",
      confidence: 1,
      sourceId:
        "source-control-plane",
      documentId:
        "doc-northstar-motion",
      chunkId:
        "chunk-doc-northstar-motion-001",
      entityIds: [
        "entity-northstar",
      ],
      observedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        requiredEvidence: [
          "CRM contact data",
          "Account research",
        ],
      },
    },

    {
      id: "claim-ci-value",
      statement:
        "The CI Economics V1.1.0 base scenario models approximately $391,910 in annual customer value against a $120,000 annual price.",
      state: "MODELED",
      provenance: "MODELED",
      confidence: 0.6,
      sourceId:
        "source-demo-economics",
      documentId:
        "doc-ci-economics",
      chunkId:
        "chunk-doc-ci-economics-001",
      entityIds: [
        "entity-ci-economics",
        "entity-northstar",
        "entity-warpbuild-ci",
      ],
      observedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        modelVersion:
          "1.1.0",
      },
    },

    {
      id: "claim-experiment-portfolio",
      statement:
        "The modeled experiment portfolio selects three experiments with $48,000 allocated budget and $686,200 modeled expected value.",
      state: "MODELED",
      provenance: "MODELED",
      confidence: 0.5351,
      sourceId:
        "source-demo-experiments",
      documentId:
        "doc-experiment-portfolio",
      chunkId:
        "chunk-doc-experiment-portfolio-001",
      entityIds: [
        "entity-experiment-agent",
        "entity-experiment-portfolio",
      ],
      observedAt:
        BRAIN_DEMO_NOW,
      metadata: {
        requiresHumanReview:
          true,
      },
    },
  ];

export const demoKnowledgeEvidence:
  KnowledgeEvidence[] =
    demoKnowledgeClaims.map(
      (claim) => ({
        id:
          `evidence-${claim.id}`,
        claimId:
          claim.id,
        sourceId:
          claim.sourceId,
        documentId:
          claim.documentId,
        chunkId:
          claim.chunkId,
        excerpt:
          claim.statement,
        reliability:
          claim.provenance ===
          "INTERNAL"
            ? 1
            : claim.provenance ===
                "PUBLIC"
              ? 0.85
              : claim.provenance ===
                  "MODELED"
                ? 0.6
                : 0.35,
        observedAt:
          claim.observedAt,
      }),
    );

export const demoKnowledgeRelations:
  KnowledgeRelation[] = [
    {
      id: "relation-warpbuild-ci",
      fromEntityId:
        "entity-warpbuild",
      toEntityId:
        "entity-warpbuild-ci",
      type: "OWNS",
      description:
        "WarpBuild is represented as the company behind WarpBuild CI.",
      evidenceIds: [
        "evidence-claim-warpbuild-ci",
      ],
      confidence: 0.85,
    },

    {
      id: "relation-northstar-motion",
      fromEntityId:
        "entity-revenue-agent",
      toEntityId:
        "entity-northstar",
      type: "TARGETS",
      description:
        "Revenue Intelligence generated the synthetic Northstar enterprise motion.",
      evidenceIds: [
        "evidence-claim-northstar-motion",
      ],
      confidence: 0.7658,
    },

    {
      id: "relation-economics-northstar",
      fromEntityId:
        "entity-ci-economics",
      toEntityId:
        "entity-northstar",
      type: "MEASURES",
      description:
        "The deterministic CI economics scenario is applied to the synthetic Northstar account model.",
      evidenceIds: [
        "evidence-claim-ci-value",
      ],
      confidence: 0.6,
    },

    {
      id: "relation-experiment-decision",
      fromEntityId:
        "entity-experiment-agent",
      toEntityId:
        "entity-experiment-portfolio",
      type: "INFORMS",
      description:
        "Experiment Analyst informs the modeled portfolio decision.",
      evidenceIds: [
        "evidence-claim-experiment-portfolio",
      ],
      confidence: 0.5351,
    },
  ];